Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
  # Customize your Aurora Serverless cluster by setting the default value of the following parameters.
  mysqlDBName:
    Type: String
    Description: The name of the initial database to be created in the DB cluster.
    Default: sampleprod
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  mysqlDBAutoPauseSeconds:
    Type: Number
    Description: The duration in seconds before the cluster pauses.
    Default: 1000
Mappings:
  mysqlEnvScalingConfigurationMap: 
    prod:
      "DBMinCapacity": 1 # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256]
      "DBMaxCapacity": 1 # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256]
    All:
      "DBMinCapacity": 1 # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256]
      "DBMaxCapacity": 1 # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256]

Resources:
  mysqlDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group of Copilot private subnets for Aurora cluster.
      SubnetIds:
        !Split [',', { 'Fn::ImportValue': !Sub '${App}-${Env}-PrivateSubnets' }]
  mysqlSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your workload to access the DB cluster mysql'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'The Security Group for ${Name} to access DB cluster mysql.'
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-${Name}-Aurora'
  mysqlDBClusterSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your DB cluster mysql'
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the database cluster.
      SecurityGroupIngress:
        - ToPort: 3306
          FromPort: 3306
          IpProtocol: tcp
          Description: !Sub 'From the Aurora Security Group of the workload ${Name}.'
          SourceSecurityGroupId: !Ref mysqlSecurityGroup
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
  mysqlAuroraSecret:
    Metadata:
      'aws:copilot:description': 'A Secrets Manager secret to store your DB credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  mysqlDBClusterParameterGroup:
    Metadata:
      'aws:copilot:description': 'A DB parameter group for engine configuration values'
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: !Ref 'AWS::StackName'
      Family: 'aurora-mysql5.7'
      Parameters:
        innodb_large_prefix: "1"
        innodb_file_per_table: "1"
        innodb_file_format: Barracuda
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_database: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4
        collation_server: utf8mb4_general_ci
        collation_connection: utf8mb4_general_ci
  mysqlDBCluster:
    Metadata:
      'aws:copilot:description': 'The mysql Aurora Serverless database cluster'
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername:
        !Join [ "",  [ '{{resolve:secretsmanager:', !Ref mysqlAuroraSecret, ":SecretString:username}}" ]]
      MasterUserPassword:
        !Join [ "",  [ '{{resolve:secretsmanager:', !Ref mysqlAuroraSecret, ":SecretString:password}}" ]]
      DatabaseName: !Ref mysqlDBName
      Engine: 'aurora-mysql'
      EngineVersion: '5.7.mysql_aurora.2.07.1'
      EngineMode: serverless
      EnableHttpEndpoint: true
      DBClusterParameterGroupName: !Ref mysqlDBClusterParameterGroup
      DBSubnetGroupName: !Ref mysqlDBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref mysqlDBClusterSecurityGroup
      ScalingConfiguration:
        AutoPause: true
        # Replace "All" below with "!Ref Env" to set different autoscaling limits per environment.
        MinCapacity: !FindInMap [mysqlEnvScalingConfigurationMap, All, DBMinCapacity]
        MaxCapacity: !FindInMap [mysqlEnvScalingConfigurationMap, All, DBMaxCapacity]
        SecondsUntilAutoPause: !Ref mysqlDBAutoPauseSeconds
  mysqlSecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref mysqlAuroraSecret
      TargetId: !Ref mysqlDBCluster
      TargetType: AWS::RDS::DBCluster
Outputs:
  auroraResourceArn:
    Description: "Aurora Serverless Resource ARN"
    Value: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${mysqlDBCluster}'
    Export:
      Name: !Sub '${Env}AuroraClusterArn'
  auroraSecretsArn: # injected as MYSQL_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref mysqlAuroraSecret
    Export:
      Name: !Sub '${Env}AuroraSecretArn'
  mysqlSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref mysqlSecurityGroup
