test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

localstack:
  service: S3
  access_key_id: local
  secret_access_key: local
  region: ap-northeast-1
  endpoint: http://localstack:4566
  force_path_style: true
  bucket: sample-app

amazon:
  service: S3
  access_key_id:     <%= ENV['AWS_STORAGE_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_STORAGE_SECRET_ACCESS_KEY'] %>
  region:            <%= ENV['AWS_STORAGE_REGION'] %>
  bucket:            <%= ENV['AWS_STORAGE_BUCKET'] %>
